### PR TITLE
Add events accept mutex delay

### PR DESCRIPTION
**Pull request by mlrobinson**
Adding the option to manage accept mutex and accept mutex delay. Defaults taken from here: http://nginx.org/en/docs/ngx_core_module.html#accept_mutex.

### CODE REVIEW

**Comment by mlrobinson** [comment]
All tests for Puppet 4 failed, including everything I didn't touch... should I have pulled from a different branch?

**Comment by jfryman** [comment]
It's entirely possible travis failed. Let's see. Re-running.

**Comment by jfryman** [comment]
Hmmm. Looks like it's still failing. As long as master is up to date, it should be ok... :/

**Comment by 3flex** [comment]
It's an issue in rspec-puppet. It should be fixed in rspec-puppet 2.3.2 which was released yesterday.

Looks safe to merge.

**Comment by mlrobinson** [comment]
Do I need to do anything to help get this merged in?

**Comment by jfryman** [comment]
Nope, not at all! Re-ran the checks, all passed! Thanks for the contribution! :bow:

**Pull request merged**
