### PR TITLE
Issue_749  Add 'managed by puppet' to config files

### PR DESCRIPTION
**Pull request by alexharv074**

### CODE REVIEW

**Comment by bdronneau** [comment]
:+1:

**Comment by alexharv074** [comment]
If possible, can someone more familiar with the code (& how Nginx works) double check that I didn't miss any files that also should have this message?

**Comment by alexharv074** [comment]
Hi @jfryman any chance I could get these PRs I opened reviewed and merged?

**Comment by 3flex** [comment]
Can also add to first line of:
* templates/conf.d/geo.erb
* templates/mailhost/mailhost.erb
* templates/mailhost/mailhost_ssl.erb
* templates/conf.d/map.erb
* templates/streamhost/streamhost.erb

Since there's no shared header file between mailhost.erb and mailhost_ssl.erb it's possible that the note will be added twice, but that's not a major concern.

**Comment by alexharv074** [comment]
Ok, done.

**Pull request merged**
