### PR TITLE
Multiple proxy_cache_path entries

### PR DESCRIPTION
**Pull request by jacobmw**
Adding ability to specify multiple proxy_cache_path entries with unique proxy_cache_keys_zone values

### CODE REVIEW

**Comment by 3flex** [comment]
Couple of things:

* Please add tests
* Please build this capability into the existing `proxy_cache_path` parameter then populate the template using the new code after checking if the value `is_a?(Hash)`, and using the existing code if it's not.

**Comment by jacobmw** [comment]
Rebuilt this capability into the existing proxy_cache_path parameter and added proper validation.

**Comment by pashamesh** [comment]
Why this pull request not merged yet?

**Comment by jfryman** [comment]
@pashamesh why? because you haven't asked yet. :)

**Comment by pashamesh** [comment]
Thanks a lot :)

**Comment by jacobmw** [comment]
Wow, thanks, forgot all about this one.  I guess now I can go point my Puppetfile back at this repo :)

**Pull request merged**
