### PR TITLE
Mitigating Httpoxy 

### PR DESCRIPTION
**Pull request by marcofl**
Should possibly go together with https://github.com/jfryman/puppet-nginx/compare/httpoxy-test
If you guys are already working on a httpoxy fix, just reject this pull request. 
Thanks.

### CODE REVIEW

**Comment by dasrecht** [comment]
Looks good to me 👍

**Comment by FlorianSW** [comment]
Looks good to me  :ok_hand:

**Comment by jfryman** [comment]
Stellar. Tyvm for the code!

**Comment by dominics** [comment]
Note that this fix was reverted as part of #862

That seems to be because Nginx recommend overriding the header just for PHP requests (https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/#connecting-nginx-to-php-fpm) - not a great solution IMO considering there is exactly zero legitimate use for a `Proxy` header in HTTP.

And the "upstream version" copied as part of that predates the (re)discovery of the vulnerability.

Upshot is that when people upgrade to 0.7.0 of this library, their mitigation will come undone.

**Pull request merged**
