### PR TITLE
Support ssl client verify

### PR DESCRIPTION
**Pull request by jamescarr**
This adds support for `ssl_client_verify`, closing #581!

### CODE REVIEW

**Comment by jfryman** [comment]
Nice! Thanks for the code. Would you mind also adding tests?

**Comment by jamescarr** [comment]
Sure thing!

**Comment by jamescarr** [comment]
That should do it. Awaiting test results but I think we're good now.

**Comment by jfryman** [comment]
Excellent! Thank you again!

**Pull request merged**
