### PR TITLE
restart replaced with reload in service_spec.rb file

### PR DESCRIPTION
**Pull request by pallavjosh**
@jfryman related with pull request 702 comment from me. review ad confirm please.
https://github.com/jfryman/puppet-nginx/pull/702

### CODE REVIEW

**Comment by 3flex** [comment]
@pallavjosh this PR is only updating the tests, you would also need to update the Puppet manifests themselves.

Also please be careful with your spelling, the command would be `reload` not `relaod`

**Comment by pallavjosh** [comment]
@3flex Sorry for the typo, corrected. Though in this case manifest is already changed with pull request #702 #712 , test was unchanged. So changing test file only with this PR
 
If In case upstream was wrong still shooting error as execution of "/etc/init.d/nginx restart" command failed. That pointed out issue.

**Comment by pallavjosh** [comment]
@jfryman Please review, merge and confirm on reload part. Thanks

**Comment by jfryman** [comment]
@pallavjosh Thanks so much for the contribution! 🎩🙇🏽

**Pull request merged**
