### PR TITLE
Add nginx_version fact

### PR DESCRIPTION
**Pull request by jyaworski**

### CODE REVIEW

**Comment by 3flex** [comment]
Please add a test for this. Can use https://github.com/puppetlabs/puppetlabs-mysql/commit/3ce8ad3799803cbd34d42a4b39ec27b914e9abd6 as a template.

**Comment by jyaworski** [comment]
@3flex done. Thanks.

**Comment by jyaworski** [comment]
Hmm. I'm not familiar with testing this particular fact type. Let me look into it; the test fails, but the fact works.

**Comment by jyaworski** [comment]
OK, I got it. I forgot to stub :which.

**Comment by 3flex** [comment]
Looks good. Hopefully obvious, but did you confirm it works on a real machine?

**Comment by jyaworski** [comment]
Using it in production now, actually.

**Comment by 3flex** [comment]
@jyaworski I'm proposing this be reverted (see #760) because it's not supported by earlier versions of Facter which are still supported by this module.

Are you able to make a version that is compatible back to Facter 1.7? If so, please submit a new PR. Thanks!

**Pull request merged**
